'use client';
import { React, useEffect } from 'react'
import AOS from 'aos';
import 'aos/dist/aos.css';
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Cumulation',
//   description: 'Generated by pirate07',
// }

const RootLayout = ({ children }) => {
  useEffect(() => {
    AOS.init({
         duration: 800,
         once: false,
       })
 }, [])
  return (
    <html lang="en">
      <Head>
        <title>Cumulation</title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export default RootLayout;